apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "matomo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: matomo-data
          persistentVolumeClaim:
            claimName: {{ include "matomo.fullname" . }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: matomo-data
              mountPath: /data
            {{- end }}
          env:
          - name: MATOMO_DATABASE_TABLES_PREFIX
            value: matomo_
          - name: MATOMO_INDEX
            value: http://localhost/index.php
          - name: MATOMO_DATABASE_TYPE
            value: InnoDB
          - name: MATOMO_DATABASE_ADAPTER
            value: 'PDO\MYSQL'
          - name: MATOMO_DATABASE_USERNAME
            value: {{ .Values.mariadb.user }}
          - name: MATOMO_DATABASE_DBNAME
            value: {{ .Values.mariadb.name }}
          - name: MATOMO_DATABASE_PASSWORD
            value: {{ .Values.mariadb.password }}
          - name: MATOMO_DATABASE_HOST
            value: {{ include "matomo.fullname" . }}-mariadb
          - name: MATOMO_SUPERUSER_USERNAME
            value: matomo
          - name: MATOMO_SUPERUSER_PASSWORD
            value: matomo
          - name: MATOMO_SUPERUSER_EMAIL
            value: mail@mail.mail
          - name: MATOMO_SITENAME
            value: matomo
          - name: MATOMO_TIMEZONE
            value: America/New_York
          # # - name: MYSQL_ROOT_PASSWORD
          #   value: {{ .Values.mariadb.rootPassword }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
