apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "matomo.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}